#:kivy 2.3.0

<Modem>:
    orientation: "vertical"

    TextInput:
        id: userInput
    Label:
        id: labelText # This id isn't currently serving a purpose
        text: root.readData()
    Button:
        text: 'Done'
        on_release:
            data = userInput.text
            root.saveData(data, gratitude)

    #when button pressed save input to file
    #return Label(text='read file')




#search 
#log
#graphs