#:kivy 2.3.0

<ModemScreen>:
    orientation: "vertical"

    TextInput:
        id: userInput
    Label:
        id: labelText # This id isn't serving a purpose
        text: root.readData()
    Button:
        text: 'Done'
        on_release:
            gratitude = userInput.text
            root.saveData(gratitude, 1)

    #when button pressed save input to file
    #return Label(text='read file')




#search 
#log
#graphs